name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        run: |
          git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .
          git checkout "$GITHUB_REF_NAME"

      - name: Setup
        run: |
          bin/setup.sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      
      - name: CI
        run: bin/ci.sh
