name: Run `pre-commit` on PRs

on:
  pull_request:
    branches: [main, qa, dev]
  push:
    branches: [main, qa, dev]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry install
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
